var hierarchy =
[
    [ "__vcrt_ptd", "struct____vcrt__ptd.html", null ],
    [ "_DPN_CONNECTION_INFO", "struct___d_p_n___c_o_n_n_e_c_t_i_o_n___i_n_f_o.html", null ],
    [ "ACTION_DEBUGMSG_DATA", "struct_a_c_t_i_o_n___d_e_b_u_g_m_s_g___d_a_t_a.html", null ],
    [ "AUTOBUY_CARTITEM", "struct_a_u_t_o_b_u_y___c_a_r_t_i_t_e_m.html", null ],
    [ "BASE_INFO", "struct_b_a_s_e___i_n_f_o.html", null ],
    [ "BET", "struct_b_e_t.html", null ],
    [ "BLOWFISH_CTX", "struct_b_l_o_w_f_i_s_h___c_t_x.html", null ],
    [ "BOUNTY_HUNT", "struct_b_o_u_n_t_y___h_u_n_t.html", null ],
    [ "CARGO_INFO", "struct_c_a_r_g_o___i_n_f_o.html", null ],
    [ "CARGO_MISSION", "struct_c_a_r_g_o___m_i_s_s_i_o_n.html", null ],
    [ "CCmds", "class_c_cmds.html", [
      [ "CConsole", "class_c_console.html", null ],
      [ "CInGame", "class_c_in_game.html", null ],
      [ "CSocket", "class_c_socket.html", null ]
    ] ],
    [ "CLIENT_DATA", "struct_c_l_i_e_n_t___d_a_t_a.html", null ],
    [ "CLIENT_INFO", "struct_c_l_i_e_n_t___i_n_f_o.html", null ],
    [ "CLOAK_ARCH", "struct_c_l_o_a_k___a_r_c_h.html", null ],
    [ "CLOAK_INFO", "struct_c_l_o_a_k___i_n_f_o.html", null ],
    [ "CONNECTION_DATA", "struct_c_o_n_n_e_c_t_i_o_n___d_a_t_a.html", null ],
    [ "CONNECTION_DATA_EXCEPTION", "struct_c_o_n_n_e_c_t_i_o_n___d_a_t_a___e_x_c_e_p_t_i_o_n.html", null ],
    [ "Console", "class_console.html", null ],
    [ "contestant", "structcontestant.html", null ],
    [ "CTimer", "class_c_timer.html", null ],
    [ "DATA_MARKETITEM", "struct_d_a_t_a___m_a_r_k_e_t_i_t_e_m.html", null ],
    [ "DEFERREDJUMPS", "struct_d_e_f_e_r_r_e_d_j_u_m_p_s.html", null ],
    [ "DELAY_MARK", "struct_d_e_l_a_y___m_a_r_k.html", null ],
    [ "DOCKING_REQUEST", "struct_d_o_c_k_i_n_g___r_e_q_u_e_s_t.html", null ],
    [ "EQ_HARDPOINT", "struct_e_q___h_a_r_d_p_o_i_n_t.html", null ],
    [ "EQ_ITEM", "struct_e_q___i_t_e_m.html", null ],
    [ "std::false_type", null, [
      [ "IsVector< typename >", "struct_is_vector.html", null ]
    ] ],
    [ "FFA", "struct_f_f_a.html", null ],
    [ "FLHOOK_PLAYER_DATA", "struct_f_l_h_o_o_k___p_l_a_y_e_r___d_a_t_a.html", null ],
    [ "PluginManager::FunctionHookProps", "struct_plugin_manager_1_1_function_hook_props.html", null ],
    [ "GROUP_MEMBER", "struct_g_r_o_u_p___m_e_m_b_e_r.html", null ],
    [ "HK_ERROR_INFO", "struct_h_k___e_r_r_o_r___i_n_f_o.html", null ],
    [ "HKPLAYERINFO", "struct_h_k_p_l_a_y_e_r_i_n_f_o.html", null ],
    [ "HookEntry", "struct_hook_entry.html", null ],
    [ "HYPERSPACE_COORDS", "struct_h_y_p_e_r_s_p_a_c_e___c_o_o_r_d_s.html", null ],
    [ "IGNORE_INFO", "struct_i_g_n_o_r_e___i_n_f_o.html", null ],
    [ "INFO", "struct_i_n_f_o.html", null ],
    [ "INISECTIONVALUE", "struct_i_n_i_s_e_c_t_i_o_n_v_a_l_u_e.html", null ],
    [ "ITEM_INFO", "struct_i_t_e_m___i_n_f_o.html", null ],
    [ "JUMPDRIVE", "struct_j_u_m_p_d_r_i_v_e.html", null ],
    [ "JUMPDRIVE_ARCH", "struct_j_u_m_p_d_r_i_v_e___a_r_c_h.html", null ],
    [ "JUMPPOINT", "class_j_u_m_p_p_o_i_n_t.html", null ],
    [ "HkIEngine::LOAD_REP_DATA", "struct_hk_i_engine_1_1_l_o_a_d___r_e_p___d_a_t_a.html", null ],
    [ "LOOTABLE_ZONE", "struct_l_o_o_t_a_b_l_e___z_o_n_e.html", null ],
    [ "MailCommunicator::MailSent", "struct_mail_communicator_1_1_mail_sent.html", null ],
    [ "MARK_INFO", "struct_m_a_r_k___i_n_f_o.html", null ],
    [ "MARKET_ITEM", "struct_m_a_r_k_e_t___i_t_e_m.html", null ],
    [ "Module", "class_module.html", [
      [ "BuildModule", "class_build_module.html", null ],
      [ "CoreModule", "class_core_module.html", null ],
      [ "DefenseModule", "class_defense_module.html", null ],
      [ "FactoryModule", "class_factory_module.html", null ],
      [ "ShieldModule", "class_shield_module.html", null ],
      [ "StorageModule", "class_storage_module.html", null ]
    ] ],
    [ "MONEY_FIX", "struct_m_o_n_e_y___f_i_x.html", null ],
    [ "MOVE", "struct_m_o_v_e.html", null ],
    [ "msvc__CatchableType", "structmsvc_____catchable_type.html", null ],
    [ "msvc__CatchableTypeArray", "structmsvc_____catchable_type_array.html", null ],
    [ "msvc__PMD", "structmsvc_____p_m_d.html", null ],
    [ "msvc__ThrowInfo", "structmsvc_____throw_info.html", null ],
    [ "msvc__TypeDescriptor", "structmsvc_____type_descriptor.html", null ],
    [ "MULTIKILLMESSAGE", "struct_m_u_l_t_i_k_i_l_l_m_e_s_s_a_g_e.html", null ],
    [ "StartupCache::NameInfo", "struct_startup_cache_1_1_name_info.html", null ],
    [ "NEWS_ITEM", "struct_n_e_w_s___i_t_e_m.html", null ],
    [ "NPC", "struct_n_p_c.html", null ],
    [ "NPC_ARCHTYPESSTRUCT", "struct_n_p_c___a_r_c_h_t_y_p_e_s_s_t_r_u_c_t.html", null ],
    [ "NPC_FLEETSTRUCT", "struct_n_p_c___f_l_e_e_t_s_t_r_u_c_t.html", null ],
    [ "NPC_MISSION", "struct_n_p_c___m_i_s_s_i_o_n.html", null ],
    [ "PATCH_INFO", "struct_p_a_t_c_h___i_n_f_o.html", null ],
    [ "PATCH_INFO_ENTRY", "struct_p_a_t_c_h___i_n_f_o___e_n_t_r_y.html", null ],
    [ "PLAYER_BONUS", "struct_p_l_a_y_e_r___b_o_n_u_s.html", null ],
    [ "PlayerBase", "class_player_base.html", null ],
    [ "PluginCommunicator", null, [
      [ "BaseCommunicator", "class_base_communicator.html", null ],
      [ "ConDataCommunicator", "class_con_data_communicator.html", null ],
      [ "MailCommunicator", "class_mail_communicator.html", null ],
      [ "TempBanCommunicator", "class_temp_ban_communicator.html", null ]
    ] ],
    [ "PluginData", "struct_plugin_data.html", null ],
    [ "PluginHookData", "struct_plugin_hook_data.html", null ],
    [ "PluginInfo", "struct_plugin_info.html", null ],
    [ "RECIPE", "struct_r_e_c_i_p_e.html", null ],
    [ "Reflectable", "struct_reflectable.html", [
      [ "Config", "struct_config.html", null ]
    ] ],
    [ "RENAME", "struct_r_e_n_a_m_e.html", null ],
    [ "HkIEngine::REP_DATA_LIST", "struct_hk_i_engine_1_1_r_e_p___d_a_t_a___l_i_s_t.html", null ],
    [ "REPAIR_ITEM", "struct_r_e_p_a_i_r___i_t_e_m.html", null ],
    [ "RESOLVE_IP", "struct_r_e_s_o_l_v_e___i_p.html", null ],
    [ "RESTART", "struct_r_e_s_t_a_r_t.html", null ],
    [ "SEHException", "struct_s_e_h_exception.html", null ],
    [ "SENSOR", "struct_s_e_n_s_o_r.html", null ],
    [ "Serializer", "class_serializer.html", null ],
    [ "Singleton< T >", "class_singleton.html", null ],
    [ "Singleton< PluginManager >", "class_singleton.html", [
      [ "PluginManager", "class_plugin_manager.html", null ]
    ] ],
    [ "SOCKET_CONNECTION", "struct_s_o_c_k_e_t___c_o_n_n_e_c_t_i_o_n.html", null ],
    [ "SpecialChatIDs", "struct_special_chat_i_ds.html", null ],
    [ "stHelpEntry", "structst_help_entry.html", null ],
    [ "SURVEY", "struct_s_u_r_v_e_y.html", null ],
    [ "SURVEY_ARCH", "struct_s_u_r_v_e_y___a_r_c_h.html", null ],
    [ "SYSTEMINFO", "struct_s_y_s_t_e_m_i_n_f_o.html", null ],
    [ "TAG_DATA", "struct_t_a_g___d_a_t_a.html", null ],
    [ "TEMPBAN_INFO", "struct_t_e_m_p_b_a_n___i_n_f_o.html", null ],
    [ "TESTBOT", "struct_t_e_s_t_b_o_t.html", null ],
    [ "HkIServerImpl::Timer", "struct_hk_i_server_impl_1_1_timer.html", null ],
    [ "HkIServerImpl::TIMER", "struct_hk_i_server_impl_1_1_t_i_m_e_r.html", null ],
    [ "TIMER", "struct_t_i_m_e_r.html", null ],
    [ "TransformMatrix", "struct_transform_matrix.html", null ],
    [ "TRIGGER_ARG", "struct_t_r_i_g_g_e_r___a_r_g.html", null ],
    [ "std::true_type", null, [
      [ "IsVector< std::vector< T, A > >", "struct_is_vector_3_01std_1_1vector_3_01_t_00_01_a_01_4_01_4.html", null ]
    ] ],
    [ "USERCMD", "struct_u_s_e_r_c_m_d.html", null ],
    [ "Wildcard", "class_wildcard.html", null ],
    [ "ZONE", "struct_z_o_n_e.html", null ],
    [ "ZONE_BONUS", "struct_z_o_n_e___b_o_n_u_s.html", null ]
];