var modules =
[
    [ "Away from Keyboard", "group___away_from_keyboard.html", "group___away_from_keyboard" ],
    [ "Anti Jump Disconnect", "group___anti_jump_disconnect.html", "group___anti_jump_disconnect" ],
    [ "Arena", "group___arena.html", "group___arena" ],
    [ "Autobuy", "group___autobuy.html", null ],
    [ "Betting", "group___betting.html", "group___betting" ],
    [ "Bounty Hunt", "group___bounty_hunt.html", "group___bounty_hunt" ],
    [ "Cargo Drop", "group___cargo_drop.html", "group___cargo_drop" ],
    [ "Cash Manager", "group___cash_manager.html", "group___cash_manager" ],
    [ "Connection Data", "group___condata.html", "group___condata" ],
    [ "Crash Catcher", "group___crash_catcher.html", "group___crash_catcher" ],
    [ "Daily Tasks", "group___daily_tasks.html", "group___daily_tasks" ],
    [ "Death Penalty", "group___death_penalty.html", "group___death_penalty" ],
    [ "Event", "group___event.html", "group___event" ],
    [ "IP Ban", "group___i_p_ban.html", "group___i_p_ban" ],
    [ "Kill Tracker", "group___kill_tracker.html", "group___kill_tracker" ],
    [ "Light Control", "group___light_control.html", "group___light_control" ],
    [ "Loot Tables", "group___loot_tables.html", "group___loot_tables" ],
    [ "Mark", "group___mark.html", "group___mark" ],
    [ "Message", "group___message.html", "group___message" ],
    [ "Mining Control", "group___mining_control.html", "group___mining_control" ],
    [ "Misc Commands", "group___misc_commands.html", "group___misc_commands" ],
    [ "NPC Control", "group___n_p_c_control.html", "group___n_p_c_control" ],
    [ "Stats", "group___stats.html", "group___stats" ],
    [ "Purchase Restrictions", "group___purchase_restrictions.html", null ],
    [ "Rename", "group___rename.html", null ],
    [ "Solar Control", "group___solar_control.html", "group___solar_control" ],
    [ "Sound Manager", "group___sound_manager.html", null ],
    [ "System Sensor", "group___system_sensor.html", null ],
    [ "Tax", "group___tax.html", null ],
    [ "Wardrobe", "group___wardrobe.html", null ],
    [ "Warehouse", "group___warehouse.html", null ]
];