var namespace_plugins =
[
    [ "Afk", "namespace_plugins_1_1_afk.html", "namespace_plugins_1_1_afk" ],
    [ "AntiJumpDisconnect", "namespace_plugins_1_1_anti_jump_disconnect.html", "namespace_plugins_1_1_anti_jump_disconnect" ],
    [ "Arena", "namespace_plugins_1_1_arena.html", "namespace_plugins_1_1_arena" ],
    [ "Autobuy", "namespace_plugins_1_1_autobuy.html", "namespace_plugins_1_1_autobuy" ],
    [ "Betting", "namespace_plugins_1_1_betting.html", "namespace_plugins_1_1_betting" ],
    [ "BountyHunt", "namespace_plugins_1_1_bounty_hunt.html", "namespace_plugins_1_1_bounty_hunt" ],
    [ "CargoDrop", "namespace_plugins_1_1_cargo_drop.html", "namespace_plugins_1_1_cargo_drop" ],
    [ "CashManager", "namespace_plugins_1_1_cash_manager.html", "namespace_plugins_1_1_cash_manager" ],
    [ "ConData", "namespace_plugins_1_1_con_data.html", "namespace_plugins_1_1_con_data" ],
    [ "CrashCatcher", "namespace_plugins_1_1_crash_catcher.html", "namespace_plugins_1_1_crash_catcher" ],
    [ "DeathPenalty", "namespace_plugins_1_1_death_penalty.html", "namespace_plugins_1_1_death_penalty" ],
    [ "Event", "namespace_plugins_1_1_event.html", "namespace_plugins_1_1_event" ],
    [ "IPBan", "namespace_plugins_1_1_i_p_ban.html", [
      [ "AdminCmd_AuthenticateChar", "group___i_p_ban.html#gaaccbc2f281e87d0f61410f7dc4b4771f", null ],
      [ "AdminCmd_ReloadBans", "group___i_p_ban.html#ga9f403fe739de471046a7bd9451ef61e6", null ],
      [ "BaseEnter", "group___i_p_ban.html#ga93cdcddc3cd0833db4917192d3ade83b", null ],
      [ "ClearClientInfo", "group___i_p_ban.html#gabb899eb1e225b47542693b5f18e7179d", null ],
      [ "CmdHelp_Callback", "group___i_p_ban.html#ga13d1bdeedeaaf4dc0daf32a54e844ac9", null ],
      [ "ExecuteCommandString_Callback", "group___i_p_ban.html#ga957de83ac423a476b4c30b3830f29e43", null ],
      [ "LoadSettings", "namespace_plugins_1_1_i_p_ban.html#a45f649e31ad303f00a6ff7742abbbda0", null ],
      [ "PlayerLaunch", "group___i_p_ban.html#gaeebf2d67e6a9e0388aaf6e47de6aacab", null ],
      [ "global", "namespace_plugins_1_1_i_p_ban.html#a97486146ef3222e8eab0c4ca684ba00e", null ]
    ] ],
    [ "KillTracker", "namespace_plugins_1_1_kill_tracker.html", "namespace_plugins_1_1_kill_tracker" ],
    [ "LightControl", "namespace_plugins_1_1_light_control.html", "namespace_plugins_1_1_light_control" ],
    [ "Mark", "namespace_plugins_1_1_mark.html", "namespace_plugins_1_1_mark" ],
    [ "Message", "namespace_plugins_1_1_message.html", "namespace_plugins_1_1_message" ],
    [ "MiningControl", "namespace_plugins_1_1_mining_control.html", "namespace_plugins_1_1_mining_control" ],
    [ "MiscCommands", "namespace_plugins_1_1_misc_commands.html", "namespace_plugins_1_1_misc_commands" ],
    [ "Npc", "namespace_plugins_1_1_npc.html", "namespace_plugins_1_1_npc" ],
    [ "PurchaseRestrictions", "namespace_plugins_1_1_purchase_restrictions.html", "namespace_plugins_1_1_purchase_restrictions" ],
    [ "Rename", "namespace_plugins_1_1_rename.html", "namespace_plugins_1_1_rename" ],
    [ "Restart", "namespace_plugins_1_1_restart.html", "namespace_plugins_1_1_restart" ],
    [ "SoundManager", "namespace_plugins_1_1_sound_manager.html", "namespace_plugins_1_1_sound_manager" ],
    [ "SpinProtection", "namespace_plugins_1_1_spin_protection.html", "namespace_plugins_1_1_spin_protection" ],
    [ "Stats", "namespace_plugins_1_1_stats.html", "namespace_plugins_1_1_stats" ],
    [ "SystemSensor", "namespace_plugins_1_1_system_sensor.html", "namespace_plugins_1_1_system_sensor" ],
    [ "Tax", "namespace_plugins_1_1_tax.html", "namespace_plugins_1_1_tax" ],
    [ "Template", "namespace_plugins_1_1_template.html", "namespace_plugins_1_1_template" ],
    [ "Wardrobe", "namespace_plugins_1_1_wardrobe.html", "namespace_plugins_1_1_wardrobe" ],
    [ "Warehouse", "namespace_plugins_1_1_warehouse.html", "namespace_plugins_1_1_warehouse" ]
];