#include "PCH.hpp"

#include "Core/ClientServerInterface.hpp"

#define Cast reinterpret_cast<FARPROC>

std::array<IServerImplHook::HookEntry, 73> IServerImplHook::entries = {
    {
     { Cast(SubmitChat), -0x008, nullptr },
     { Cast(FireWeapon), 0x000, nullptr },
     { Cast(ActivateEquip), 0x004, nullptr },
     { Cast(ActivateCruise), 0x008, nullptr },
     { Cast(ActivateThrusters), 0x00C, nullptr },
     { Cast(SetTarget), 0x010, nullptr },
     { Cast(TractorObjects), 0x014, nullptr },
     { Cast(GoTradelane), 0x018, nullptr },
     { Cast(StopTradelane), 0x01C, nullptr },
     { Cast(JettisonCargo), 0x020, nullptr },
     { Cast(DisConnect), 0x040, nullptr },
     { Cast(OnConnect), 0x044, nullptr },
     { Cast(Login), 0x048, nullptr },
     { Cast(CharacterInfoReq), 0x04C, nullptr },
     { Cast(CharacterSelect), 0x050, nullptr },
     { Cast(CreateNewCharacter), 0x058, nullptr },
     { Cast(DestroyCharacter), 0x05C, nullptr },
     { Cast(ReqShipArch), 0x064, nullptr },
     { Cast(ReqHullStatus), 0x068, nullptr },
     { Cast(ReqCollisionGroups), 0x06C, nullptr },
     { Cast(ReqEquipment), 0x070, nullptr },
     { Cast(ReqAddItem), 0x078, nullptr },
     { Cast(ReqRemoveItem), 0x07C, nullptr },
     { Cast(ReqModifyItem), 0x080, nullptr },
     { Cast(ReqSetCash), 0x084, nullptr },
     { Cast(ReqChangeCash), 0x088, nullptr },
     { Cast(BaseEnter), 0x08C, nullptr },
     { Cast(BaseExit), 0x090, nullptr },
     { Cast(LocationEnter), 0x094, nullptr },
     { Cast(LocationExit), 0x098, nullptr },
     { Cast(BaseInfoRequest), 0x09C, nullptr },
     { Cast(LocationInfoRequest), 0x0A0, nullptr },
     { Cast(GfObjSelect), 0x0A4, nullptr },
     { Cast(GFGoodVaporized), 0x0A8, nullptr },
     { Cast(MissionResponse), 0x0AC, nullptr },
     { Cast(TradeResponse), 0x0B0, nullptr },
     { Cast(GFGoodBuy), 0x0B4, nullptr },
     { Cast(GFGoodSell), 0x0B8, nullptr },
     { Cast(SystemSwitchOutComplete), 0x0BC, nullptr },
     { Cast(PlayerLaunch), 0x0C0, nullptr },
     { Cast(LaunchComplete), 0x0C4, nullptr },
     { Cast(JumpInComplete), 0x0C8, nullptr },
     { Cast(Hail), 0x0CC, nullptr },
     { Cast(SpObjUpdate), 0x0D0, nullptr },
     { Cast(SpMunitionCollision), 0x0D4, nullptr },
     { Cast(SpObjCollision), 0x0DC, nullptr },
     { Cast(SpRequestUseItem), 0x0E0, nullptr },
     { Cast(SpRequestInvincibility), 0x0E4, nullptr },
     { Cast(RequestEvent), 0x0F0, nullptr },
     { Cast(RequestCancel), 0x0F4, nullptr },
     { Cast(MineAsteroid), 0x0F8, nullptr },
     { Cast(RequestCreateShip), 0x100, nullptr },
     { Cast(SpScanCargo), 0x104, nullptr },
     { Cast(SetManeuver), 0x108, nullptr },
     { Cast(InterfaceItemUsed), 0x10C, nullptr },
     { Cast(AbortMission), 0x110, nullptr },
     { Cast(SetWeaponGroup), 0x118, nullptr },
     { Cast(SetVisitedState), 0x11C, nullptr },
     { Cast(RequestBestPath), 0x120, nullptr },
     { Cast(RequestPlayerStats), 0x124, nullptr },
     { Cast(PopupDialog), 0x128, nullptr },
     { Cast(RequestGroupPositions), 0x12C, nullptr },
     { Cast(SetInterfaceState), 0x134, nullptr },
     { Cast(RequestRankLevel), 0x138, nullptr },
     { Cast(InitiateTrade), 0x13C, nullptr },
     { Cast(TerminateTrade), 0x140, nullptr },
     { Cast(AcceptTrade), 0x144, nullptr },
     { Cast(SetTradeMoney), 0x148, nullptr },
     { Cast(AddTradeEquip), 0x14C, nullptr },
     { Cast(DelTradeEquip), 0x150, nullptr },
     { Cast(RequestTrade), 0x154, nullptr },
     { Cast(StopTradeRequest), 0x158, nullptr },
     { Cast(Dock), 0x16C, nullptr },
     }
};

#undef Cast
